let a = window;
// alert('Hellow World');
// a = prompt('This will Distroy Your Computer.');
// a = confirm('Are You sure want to delete this page');
a = window.document;
a = window.innerHeight;
a = window.innerWidth;
a = window.outerHeight;
a = window.outerWidth;
a = scrollX;
a = scrollY;
a = location;
a = location.reload;
a = location.href;
// a = location.href = '//google.com';
a = location.toString();
a = window.history;
// a = window.history.go(-1)/(1);
// console.log (a);